[phases.setup]
aptPkgs = ["ffmpeg", "nodejs", "curl", "unzip", "pkg-config", "libavformat-dev", "libavcodec-dev", "libavdevice-dev", "libavutil-dev", "libavfilter-dev", "libswscale-dev", "libswresample-dev"]
cmds = ["curl -fsSL https://deno.land/install.sh | sh -s -- -y", "ln -sf /root/.deno/bin/deno /usr/local/bin/deno"]